; config.ini
[BASE]
DB_NAME = kenani_ferreterianicoll
DB_USER = postgres
DB_PASS = admin
DB_HOST = 127.0.0.1
DB_PORT = 5432
[BACKUP]
BU_NAME = BDPruebaFaqture
BU_STATE = False
BU_DRIVE = False
BU_TIME = 00:00:00
BU_TIME2 = 23:59:00
[MAIN]
M_DOC = True
M_ANUL = False
M_NCREDI = False
M_NVENTAS = False
M_GUIA = False
[MODELS]
DATE_HEADER = 2025-09-01
[APP]
DEBUG = False
[API]
SSL_VERIFY = False